parallel-compiler = true

[alias]
xtask = "run --package xtask --"
x = "xtask"
q = "x run --quick-run"
make = "xtask deprecated"
[registries]
ktra = { index = "https://gitlab.com/hartan/test-cargo-registry" }
